# Generated by Django 4.2 on 2023-09-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodentry',
            name='fineAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
