# Generated by Django 4.2 on 2023-09-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Acitve'), ('2', 'Complete')], max_length=3),
        ),
    ]
