# Generated by Django 4.2 on 2023-09-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('address', models.TextField(max_length=80)),
                ('contact', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='employee/images/')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.designation')),
            ],
        ),
        migrations.CreateModel(
            name='VISIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('employees', models.ManyToManyField(related_name='visits', to='employees.employee')),
                ('forestArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.forestarea')),
            ],
        ),
    ]
