# Generated by Django 4.2 on 2023-09-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offender',
            name='fineAmount',
        ),
    ]
